DEBUG 2021-04-20 16:07:04.868 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-20 16:07:04.868 UTC: 	 Running on: Linux cmslpc111.fnal.gov 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 10 08:19:23 CST 2020 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-04-20 16:07:04.868 UTC: 	 Executing command: 'status'
DEBUG 2021-04-20 16:07:04.869 UTC: 	 Found CRAB cache file /uscms/home/adas2/.crab3
ERROR 2021-04-20 16:07:04.877 UTC: 	 Error: pythia-stuff/EXO-MCsampleProductions/FullSimulation/RunIISummer20UL18/MiniAOD__CMSSW_10_6_17_patch1/src/inputs/MiniAOD_Hplusplus_M800_13TeV_test4/crab_projects/crab_MiniAOD_Hplusplus_M800_13TeV_test4 is not a valid CRAB project directory.
ERROR 2021-04-20 16:07:04.877 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: pythia-stuff/EXO-MCsampleProductions/FullSimulation/RunIISummer20UL18/MiniAOD__CMSSW_10_6_17_patch1/src/inputs/MiniAOD_Hplusplus_M800_13TeV_test4/crab_projects/crab_MiniAOD_Hplusplus_M800_13TeV_test4 is not a valid CRAB project directory.
INFO 2021-04-20 16:07:04.880 UTC: 	 Log file is /uscms_data/d3/adas2/pythia-stuff/EXO-MCsampleProductions/FullSimulation/RunIISummer20UL18/GEN__CMSSW_10_6_18/src/crab.log
